import datetime
import requests
import json
import urllib
import luadata


indytwo = [
  {
    "date" : "2022-01-30",
    "subpage" : "Arbitration report",
    "title" : "New arbitrators look at new case and antediluvian sanctions",
    "tags" : {"arbitrationreport"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Black History Month",
    "title" : "What are you doing for Black History Month?",
    "tags" : {"bias"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Crossword",
    "title" : "Cross swords with a crossword",
    "tags" : {},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Deletion report",
    "title" : "Ringing in the new year: Subject notability guideline under discussion",
    "tags" : {"afd"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Essay",
    "title" : "The prime directive",
    "tags" : {"essay"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Gallery",
    "title" : "No Spanish municipality without a photograph",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "In the media",
    "title" : "Fuzzy-headed government editing",
    "tags" : {"inthemedia", "paidadvocacy"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Interview",
    "title" : "CEO Maryana Iskander \"four weeks in\"",
    "tags" : {"foundation", "interviews", "maryanaiskander"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "News and notes",
    "title" : "Feedback for Board of Trustees election",
    "tags" : {"administrator", "board", "chinesewikipedia", "foundation", "newsandnotes"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Obituary",
    "title" : "Twofingered Typist",
    "tags" : {},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Op-Ed",
    "title" : "Identifying and rooting out climate change denial",
    "tags" : {"opinion"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Opinion",
    "title" : "Should the Wikimedia Foundation continue to accept cryptocurrency donations?",
    "tags" : {"foundation", "opinion"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Recent research",
    "title" : "Articles with higher quality ratings have fewer \"knowledge gaps\"",
    "tags" : {"goodarticles", "recentresearch", "research"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Serendipity",
    "title" : "Pooh entered the Public Domain – but Tigger has to wait two more years",
    "tags" : {},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Special report",
    "title" : "WikiEd course leads to Twitter harassment",
    "tags" : {"education", "specialreport"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "Traffic report",
    "title" : "The most viewed articles of 2021",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-01-30",
    "subpage" : "WikiProject report",
    "title" : "The Forgotten Featured",
    "tags" : {"articleassessment", "wikiprojectreport", "wikiprojects"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Arbitration report",
    "title" : "Parties remonstrate, arbs contemplate, skeptics coordinate",
    "tags" : {"arbitrationreport"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "By the numbers",
    "title" : "Does birthplace affect the frequency of Wikipedia biography articles?",
    "tags" : {"biography", "frenchwikipedia"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Crossword",
    "title" : "A Crossword, featuring Featured Articles",
    "tags" : {"crossword"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Deletion report",
    "title" : "The 10 most SHOCKING deletion discussions of February",
    "tags" : {"afd"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Featured content",
    "title" : "Featured Content returns",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "From the team",
    "title" : "Selection of a new Signpost Editor-in-Chief",
    "tags" : {"fromtheeditor"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Gallery",
    "title" : "The vintage exhibit",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Humour",
    "title" : "Notability of mailboxes",
    "tags" : {"humour"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "In the media",
    "title" : "Wiki-drama in the UK House of Commons",
    "tags" : {"coi", "foundation", "inthemedia"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "News and notes",
    "title" : "Impacts of Russian invasion of Ukraine",
    "tags" : {"newsandnotes"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "News from Diff",
    "title" : "The Wikimania 2022 Core Organizing Team",
    "tags" : {"foundation"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Opinion",
    "title" : "Why student editors are good for Wikipedia",
    "tags" : {"education", "opinion"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Recent research",
    "title" : "How editors and readers may be emotionally affected by disasters and terrorist attacks",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Serendipity",
    "title" : "War photographers: from Crimea (1850s) to the Russian invasion of Ukraine (2022)",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Special report",
    "title" : "A presidential candidate's team takes on Wikipedia",
    "tags" : {"coi", "frenchwikipedia", "specialreport"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Technology report",
    "title" : "Community Wishlist Survey results",
    "tags" : {"foundation", "tech", "technologyreport"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "Traffic report",
    "title" : "Euphoria, Pamela Anderson, lies and Netflix",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-02-27",
    "subpage" : "WikiProject report",
    "title" : "10 years of tea",
    "tags" : {"wikiprojectreport", "wikiprojects"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Arbitration report",
    "title" : "Skeptics given heavenly judgement, whirlwind of Discord drama begins to spin for tropical cyclone editors",
    "tags" : {"arbcom", "arbitrationreport"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Deletion report",
    "title" : "Ukraine, werewolves, Ukraine, YouTube pundits, and Ukraine",
    "tags" : {"mfd", "russia", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Discussion report",
    "title" : "Athletes are less notable now",
    "tags" : {"discussionreport", "mfd", "nsport", "ukraine", "universalcodeofconduct"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Disinformation report",
    "title" : "The oligarchs' socks",
    "tags" : {"coi", "paidadvocacy", "russia"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Essay",
    "title" : "Yes, the sky is blue",
    "tags" : {"essay", "verifiability"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Eyewitness Wikimedian – Kharkiv, Ukraine",
    "title" : "Countering Russian aggression with a camera",
    "tags" : {"opinion", "russia", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Eyewitness Wikimedian – Vinnytsia, Ukraine",
    "title" : "War diary",
    "tags" : {"opinion", "russia", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Eyewitness Wikimedian – Western Ukraine",
    "title" : "Working with Wikipedia helps",
    "tags" : {"opinion", "russia", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "From the archives",
    "title" : "Burn, baby burn",
    "tags" : {"backup", "fromthearchives"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "From the Signpost team",
    "title" : "We stand in solidarity with Ukraine",
    "tags" : {"fromtheeditor", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Gallery",
    "title" : "\"All we are saying is, give peace a chance...\"",
    "tags" : {"gallery", "russia", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "In the media",
    "title" : "Ukraine, Russia, and even some other stuff",
    "tags" : {"inthemedia", "russia", "russianwikipedia", "ukraine", "ukrainianwikipedia"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "News and notes",
    "title" : "Of safety and anonymity",
    "tags" : {"jimmywales", "newsandnotes", "russia", "russianwikipedia", "ukraine", "universalcodeofconduct"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "On the bright side",
    "title" : "The bright side of news",
    "tags" : {"poland", "russia", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Recent research",
    "title" : "Top scholarly citers, lack of open access references, predicting editor departures",
    "tags" : {"chinesewikipedia", "openaccess", "recentresearch", "research", "wikidata"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Technology report",
    "title" : "2022 Wikimedia Hackathon",
    "tags" : {"bot", "foundation", "hackathon", "script", "tech", "technologyreport", "vector2022"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Tips and tricks",
    "title" : "Become a keyboard ninja",
    "tags" : {"mediawiki", "regex", "wiktionary"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Traffic report",
    "title" : "War, what is it good for?",
    "tags" : {"russia", "statistics", "traffic", "trafficreport", "ukraine"},
  },
  {
    "date" : "2022-03-27",
    "subpage" : "Wikimedian perspective",
    "title" : "My heroes from Russia, Ukraine & beyond",
    "tags" : {"gallery", "russia", "ukraine"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Essay",
    "title" : "The problem with elegant variation",
    "tags" : {"essay", "synonyms"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Eyewitness Wikimedian – Vinnytsia, Ukraine",
    "title" : "War diary (Part 2)",
    "tags" : {"ukraine"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Featured content",
    "title" : "Wikipedia's best content from March",
    "tags" : {"featuredcontent", "gallery"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "From the archives",
    "title" : "Wales resigned WMF board chair in 2006 reorganization",
    "tags" : {"board", "chair", "fromthearchives", "jimbo", "moller"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Gallery",
    "title" : "A voyage around the world with WLM winners",
    "tags" : {"gallery", "wikilovesmonuments", "wikimediacommons"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Humour",
    "title" : "Really huge message boxes",
    "tags" : {"humour"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "In focus",
    "title" : "Editing difficulties on Russian Wikipedia",
    "tags" : {"infocus", "russianwikipedia", "ukraine"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "In the media",
    "title" : "The battlegrounds outside and inside Wikipedia",
    "tags" : {"coi", "disinformation", "germanwikipedia", "inthemedia"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Interview",
    "title" : "On a war and a map",
    "tags" : {"interviews", "ukraine", "wikimediacommons"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "News and notes",
    "title" : "Double trouble",
    "tags" : {"backlog", "belarus", "board", "foundation", "newsandnotes", "ombuds", "universalcodeofconduct", "vector", "wikilovesafrica"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "News from the WMF",
    "title" : "How Smart is the SMART Copyright Act?",
    "tags" : {"dmca", "licensing", "newsfromthewmf"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Recent research",
    "title" : "Student edits as \"civic engagement\"; how Wikipedia readers interact with images",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Serendipity",
    "title" : "Wikipedia loves photographs, but hates photographers",
    "tags" : {"cc", "wikimediacommons"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Special report",
    "title" : "Ukrainian Wikimedians during the war",
    "tags" : {"specialreport", "ukraine", "ukrainianwikipedia"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Technology report",
    "title" : "8-year-old attribution issues in Media Viewer",
    "tags" : {"bot", "foundation", "mediaviewer", "tech", "technologyreport"},
  },
  {
    "date" : "2022-04-24",
    "subpage" : "Traffic report",
    "title" : "Justice Jackson, the Smiths, and an invasion",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Community view",
    "title" : "Have your say in the 2022 Wikimedia Foundation Board elections",
    "tags" : {"board", "communityview"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Discussion report",
    "title" : "Portals, April Fools, admin activity requirements and more",
    "tags" : {"adminship", "discussionreport", "outing", "rfc"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Essay",
    "title" : "How not to write a Wikipedia article",
    "tags" : {"essay"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Featured content",
    "title" : "Featured content of April",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "From the archives",
    "title" : "The Onion and Wikipedia",
    "tags" : {"fromthearchives"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "From the team",
    "title" : "A changing of the guard",
    "tags" : {"fromtheeditor"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Gallery",
    "title" : "Diving under the sea for World Oceans Day",
    "tags" : {"gallery", "ocean"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Humour",
    "title" : "A new crossword",
    "tags" : {"crossword", "humour"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "In focus",
    "title" : "Measuring gender diversity in Wikipedia articles",
    "tags" : {"diversity", "frenchwikipedia", "infocus", "lgbt"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "In the media",
    "title" : "Putin, Jimbo, Musk and more",
    "tags" : {"coi", "inthemedia", "jimmywales", "russia", "russianwikipedia", "ukraine"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Interview",
    "title" : "Wikipedia's Pride",
    "tags" : {"interviews", "lgbt"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "News and notes",
    "title" : "2022 Wikimedia Board elections",
    "tags" : {"adminship", "board", "finance", "newsandnotes", "universalcodeofconduct"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "News from Diff",
    "title" : "Winners of the Human rights and Environment special nomination by Wiki Loves Earth announced",
    "tags" : {"gallery", "wikilovesearth"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "News from the WMF",
    "title" : "The EU Digital Services Act: What’s the Deal with the Deal?",
    "tags" : {"foundation", "licensing", "newsfromthewmf"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Opinion",
    "title" : "The Wikimedia Endowment – a lack of transparency",
    "tags" : {"finance", "opinion"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Recent research",
    "title" : "35 million Twitter links analysed",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Serendipity",
    "title" : "Those thieving image farms",
    "tags" : {"licensing", "wikimediacommons"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Special report",
    "title" : "Three stories of Ukrainian Wikimedians during the war",
    "tags" : {"specialreport", "ukraine", "ukrainianwikipedia"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Technology report",
    "title" : "A new video player for Wikimedia wikis",
    "tags" : {"bot", "hackathon", "script", "tech", "technologyreport"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Tips and tricks",
    "title" : "The reference desks of Wikipedia",
    "tags" : {"teahouse", "villagepump"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Traffic report",
    "title" : "Strange highs and strange lows",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "Video",
    "title" : "How the entire country of Qatar was blocked from editing",
    "tags" : {"qatar", "vandalism"},
  },
  {
    "date" : "2022-05-29",
    "subpage" : "WikiProject report",
    "title" : "WikiProject COVID-19 revisited",
    "tags" : {"covid", "wikiprojectreport", "wikiprojects"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Discussion report",
    "title" : "MoS rules on CCP name mulled, XRV axe plea nulled, mass drafting bid pulled",
    "tags" : {"blp", "china", "discussionreport", "manualofstyle", "xrv"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Essay",
    "title" : "RfA trend line haruspicy: fact or fancy?",
    "tags" : {"adminship", "essay"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Featured content",
    "title" : "Articles on Scots' clash, Yank's tux, Austrian's action flick deemed brilliant prose",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Gallery",
    "title" : "Celebration of summer, winter",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Humour",
    "title" : "Shortcuts, screwballers, Simon & Garfunkel",
    "tags" : {"crossword", "humour"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "In the media",
    "title" : "Editor given three-year sentence, big RfA makes news, Guy Standing takes it sitting down",
    "tags" : {"adminship", "coi", "inthemedia", "russianwikipedia", "ukraine"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "News and notes",
    "title" : "WMF inks new rules on government-ordered takedowns, blasts Russian feds' censor demands, spends big bucks",
    "tags" : {"finance", "foundation", "newsandnotes", "russianwikipedia", "ukraine"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "News from the WMF",
    "title" : "Wikimedia Enterprise signs first deals",
    "tags" : {"foundation", "newsfromthewmf"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Opinion",
    "title" : "Picture of the Day – how Adam plans to ru(i)n it",
    "tags" : {"gallery", "opinion", "pictureoftheday"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Recent research",
    "title" : "Wikipedia versus academia (again), tables' \"immortality\" probed",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Serendipity",
    "title" : "Was she really a Swiss lesbian automobile racer?",
    "tags" : {"dutchwikipedia", "germanwikipedia"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Special report",
    "title" : "\"Wikipedia's independence\" or \"Wikimedia's pile of dosh\"?",
    "tags" : {"finance", "foundation", "specialreport"},
  },
  {
    "date" : "2022-06-26",
    "subpage" : "Traffic report",
    "title" : "Top view counts for shows, movies, and celeb lawsuit that keeps on giving",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Arbitration report",
    "title" : "Winds of change blow for cyclone editors, deletion dustup draws toward denouement",
    "tags" : {"arbitrationreport", "xfd"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Community view",
    "title" : "Youth culture and notability",
    "tags" : {"communityview", "notability"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Deletion report",
    "title" : "This is Gonzo Country",
    "tags" : {"afd"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Discussion report",
    "title" : "Notability for train stations, notices for mobile editors, noticeboards for the rest of us",
    "tags" : {"adminship", "afd", "discussionreport", "notability"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Election guide",
    "title" : "The chosen six: 2022 Wikimedia Foundation Board of Trustees elections",
    "tags" : {"board"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Essay",
    "title" : "How to research an image",
    "tags" : {"essay"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Eyewitness Wikimedian – Vinnytsia, Ukraine",
    "title" : "War diary (part 3)",
    "tags" : {"ukraine"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Featured content",
    "title" : "A little list with surprisingly few lists",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "From the archives",
    "title" : "2012 Russian Wikipedia shutdown as it happened",
    "tags" : {"fromthearchives", "russianwikipedia"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "From the editors",
    "title" : "Rise of the machines, or something",
    "tags" : {"fromtheeditor"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Gallery",
    "title" : "A backstage pass",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Humour",
    "title" : "Why did the chicken cross the road?",
    "tags" : {"humour"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "In focus",
    "title" : "Wikidata insights from a handy little tool",
    "tags" : {"infocus", "wikidata"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "In the media",
    "title" : "Censorship, medieval hoaxes, \"pathetic supervillains\", FB-WMF AI TL bid, dirty duchess deeds done dirt cheap",
    "tags" : {"afd", "censorship", "chinesewikipedia", "coi", "hoax", "inthemedia", "lgbt", "lta", "maryanaiskander", "russianwikipedia"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "News and notes",
    "title" : "Information considered harmful",
    "tags" : {"ecosoc", "foundation", "meta", "newsandnotes", "russia", "russianwikipedia", "ukraine", "universalcodeofconduct", "wipo"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "On the bright side",
    "title" : "Ukrainian Wikimedians during the war — three (more) stories",
    "tags" : {"ukraine", "ukrainianwikipedia"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Op-Ed",
    "title" : "The \"recession\" affair",
    "tags" : {"opinion", "politics", "protection"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Opinion",
    "title" : "Criminals among us",
    "tags" : {"coi", "opinion"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Recent research",
    "title" : "A century of rulemaking on Wikipedia analyzed",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Serendipity",
    "title" : "Don't cite Wikipedia",
    "tags" : {"gallery", "wikimediacommons", "wikipedia"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Tips and tricks",
    "title" : "Cleaning up awful citations with Citation bot",
    "tags" : {"bot", "citations"},
  },
  {
    "date" : "2022-08-01",
    "subpage" : "Traffic report",
    "title" : "US TV, JP ex-PM, outer space, and politics of IN, US, UK top charts for July",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Discussion report",
    "title" : "SubscribeBoarding the Trustees",
    "tags" : {"board", "discussionreport"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Essay",
    "title" : "Delete the junk!",
    "tags" : {"afd", "essay", "votesfordeletion"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Featured content",
    "title" : "Our man drills are safe for work, but our Labia is Fausta.",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "From the archives",
    "title" : "5, 10, and 15 years ago",
    "tags" : {"foundation", "fromthearchives", "licensing", "swedishwikipedia", "wikimediacommons"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Gallery",
    "title" : "SubscribeA Fringe Affair (but not the show by Edward W. Feery that was on this year)",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Humour",
    "title" : "CommonsComix No. 1",
    "tags" : {"editwars", "humour", "wikimediacommons"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "In focus",
    "title" : "Thinking inside the box",
    "tags" : {"infocus", "userbox"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "In the media",
    "title" : "Truth or consequences? A tough month for truth",
    "tags" : {"coi", "finance", "hoax", "inthemedia", "jimmywales", "maryanaiskander", "paid", "russia", "ukraine"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "News and notes",
    "title" : "Admins wanted on English Wikipedia, IP editors not wanted on Farsi Wiki, donations wanted everywhere",
    "tags" : {"adminship", "finance", "ip", "newsandnotes", "persianwikipedia"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "News from Wiki Education",
    "title" : "18 years a Wikipedian: what it means to me",
    "tags" : {"education", "wikied"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Recent research",
    "title" : "The dollar value of \"official\" external links",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Serendipity",
    "title" : "Two photos of every library on earth",
    "tags" : {"library", "wikimediacommons"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Special report",
    "title" : "Wikimania 2022: no show, no show up?",
    "tags" : {"specialreport", "wikimania"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Technology report",
    "title" : "SubscribeVector (2022) deployment discussions happening now",
    "tags" : {"bot", "tech", "technologyreport", "vector", "wikimediacommons"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Tips and tricks",
    "title" : "The unexpected rabbit hole of typo fixing in citations...",
    "tags" : {"citation", "typo"},
  },
  {
    "date" : "2022-08-31",
    "subpage" : "Traffic report",
    "title" : "SubscribeWhat dreams (and heavily trafficked articles) may come",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "CommonsComix",
    "title" : "CommonsComix 2: Paulus Moreelse",
    "tags" : {"humour"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Discussion report",
    "title" : "Much ado about Fox News",
    "tags" : {"discussionreport", "foxnews", "newpagepatrol", "reliablesourcesnoticeboard"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Featured content",
    "title" : "Farm-fresh content",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "From the archives",
    "title" : "5, 10, and 15 Years ago: September 2022",
    "tags" : {"fromthearchives"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Gallery",
    "title" : "A Festival Descends on the City: The Edinburgh Fringe, Pt. 2",
    "tags" : {"gallery"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "In focus",
    "title" : "NPP: Still heaven or hell for new users – and for the reviewers",
    "tags" : {"finance", "foundation", "infocus", "maryanaiskander", "newpagepatrol"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "In the media",
    "title" : "A few complaints and mild disagreements",
    "tags" : {"coi", "inthemedia", "katherinemaher", "npov", "russianwikipedia"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Interview",
    "title" : "ScottishFinnishRadish's Request for Adminship",
    "tags" : {"adminship", "interviews"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "News and notes",
    "title" : "Board vote results, bot's big GET, crat chat gives new mop, WMF seeks \"sound logo\" and \"organizer lab\"",
    "tags" : {"adminship", "board", "foundation", "newsandnotes", "universalcodeofconduct"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Opinion",
    "title" : "Are we ever going to reach consensus?",
    "tags" : {"afd", "opinion"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Recent research",
    "title" : "How readers assess Wikipedia's trustworthiness, and how they could in the future",
    "tags" : {"finance", "recentresearch", "research"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Serendipity",
    "title" : "Removing watermarks, copyright signs and cigarettes from photos",
    "tags" : {"cc", "wikimediacommons"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Special report",
    "title" : "Decentralized Fundraising, Centralized Distribution",
    "tags" : {"finance", "germanwikipedia", "specialreport"},
  },
  {
    "date" : "2022-09-30",
    "subpage" : "Traffic report",
    "title" : "Kings and queens and VIPs",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "Disinformation report",
    "title" : "From Russia with WikiLove",
    "tags" : {},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "Featured content",
    "title" : "Topics, lists, submarines and Gurl.com",
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "From the archives",
    "title" : "Paid advocacy, a lawsuit over spelling mistakes, deleting Jimbo's article, and the death of Toolserver",
    "tags" : {"fromthearchives"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "From the team",
    "title" : "A new goose on the roost",
    "tags" : {"fromtheteam"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "In the media",
    "title" : "Scribing, searching, soliciting, spying, and systemic bias",
    "tags" : {"inthemedia"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "Interview",
    "title" : "Isabelle Belato on their Request for Adminship",
    "tags" : {"interviews"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "News and notes",
    "title" : "Wikipedians question Wikimedia fundraising ethics after \"somewhat-viral\" tweet",
    "tags" : {"finance", "lisaseitzgruwell", "maryanaiskander", "newsandnotes"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "News from the WMF",
    "title" : "Governance updates from, and for, the Wikimedia Endowment",
    "tags" : {"newsfromthewmf"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "Recent research",
    "title" : "Disinformatsiya: Much research, but what will actually help Wikipedia editors?",
    "tags" : {"recentresearch", "research"},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "Serendipity",
    "title" : "We all make mistakes – don’t we?",
    "tags" : {},
  },
  {
    "date" : "2022-10-31",
    "subpage" : "Traffic report",
    "title" : "Mama, they're in love with a criminal",
    "tags" : {"statistics", "traffic", "trafficreport"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Book review",
    "title" : "''Writing the Revolution''",
    "authors" : {"Jayen466"},
    "tags" : {"bookreview", "revolution", "wikipedia"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "CommonsComix",
    "title" : "Joker's trick",
    "authors" : {"Adam Cuerden"},
    "tags" : {"hoax", "humour", "wikimediacommons"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Concept",
    "title" : "The relevance of legal certainty to the English Wikipedia",
    "authors" : {},
    "tags" : {"adminship", "concept", "wikipedia"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Disinformation report",
    "title" : "Missed and Dissed",
    "authors" : {"JPxG", "Smallbones", "Adam Cuerden"},
    "tags" : {"disinformation"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Essay",
    "title" : "The Six Million FP Man",
    "authors" : {"Adam Cuerden"},
    "tags" : {"essay", "featuredpicture", "wikimediacommons"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Featured content",
    "title" : "A great month for featured articles",
    "authors" : {"Adam Cuerden"},
    "tags" : {"featuredcontent"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "From the archives",
    "title" : "Five, ten, and fifteen years ago",
    "authors" : {"Adam Cuerden", "HaeB"},
    "tags" : {"fromthearchives", "jimmywales", "otrs"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "In the media",
    "title" : "\"The most beautiful story on the Internet\"",
    "authors" : {"Bluerasberry", "Bri", "JPxG", "Smallbones"},
    "tags" : {"cryptocurrency", "finance", "foundation", "inthemedia", "vpn", "wikipedia"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Interview",
    "title" : "Lisa Seitz-Gruwell on WMF fundraising in the wake of big banner ad RfC",
    "authors" : {"The Land", "Lgruwell-WMF"},
    "tags" : {"finance", "foundation", "interviews", "lisaseitzgruwell"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "News and notes",
    "title" : "English Wikipedia editors: \"We don't need no stinking banners\"",
    "authors" : {"Adam Cuerden", "Jayen466", "Bri", "Helloheart"},
    "tags" : {"finance", "maryanaiskander", "newsandnotes"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Obituary",
    "title" : "A tribute to Michael Gäbler",
    "authors" : {"Rhododendrites", "Matthew (WMF)", "Adam Cuerden"},
    "tags" : {"obit", "wikimediacommons"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Op-Ed",
    "title" : "Diminishing returns for article quality",
    "authors" : {"Julle"},
    "tags" : {"opinion", "wikipedia"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Opinion",
    "title" : "Privacy on Wikipedia in the cyberpunk future",
    "authors" : {"Ladsgroup"},
    "tags" : {"opinion", "persianwikipedia", "spi"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Recent research",
    "title" : "Study deems COVID-19 editors smart and cool, questions of clarity and utility for WMF's proposed \"Knowledge Integrity Risk Observatory\"",
    "authors" : {"Piotrus", "HaeB"},
    "tags" : {"covid", "croatianwikipedia", "foundation", "recentresearch", "research"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Technology report",
    "title" : "Galactic dreams, encyclopedic reality",
    "authors" : {"JPxG", "Adam Cuerden", "Bri", "Smallbones"},
    "tags" : {"ai", "galactica", "tech", "technologyreport"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Tips and tricks",
    "title" : "(Wiki)break stuff",
    "authors" : {"Headbomb"},
    "tags" : {"wikibreak", "wikipediholism"},
  },
  {
    "date" : "2022-11-28",
    "subpage" : "Traffic report",
    "title" : "Musical deaths, murders, Princess Di's nominative determinism, and sports",
    "authors" : {"Igordebraga", "YttriumShrew", "SSSB"},
    "tags" : ["statistics", "traffic", "trafficreport"],
  }]

output = str(indytwo)
print(output)

# Now for the truly hoopty nonsense.

print(output)
f = open("indytwo.txt", "w")
f.write(str(output))
f.close()

outputtwo = luadata.serialize(indytwo, encoding="utf-8", indent="\t", indent_level=0)

print(outputtwo)

f = open("indythree.txt", "w")
f.write(str(outputtwo))
f.close()